import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/MainPage.module.css'

export default function MainPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <ul>
            <li>
              <Link href={'/contacts'}><a>Контакты</a></Link>
            </li>
            <li>
              <Link href={'/gallery'}><a>Галерея</a></Link>
            </li>
          </ul>
        </nav>
      </header>

      <main className={styles.main}>

      </main>

      <footer className={styles.footer}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </footer>
    </div>
  )
}
